# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0005_unique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(upload_to='blog/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/images/', verbose_name='Image'),
        ),
    ]
